alias bye='read -r '\''REPLY?Really power off? [Y/n] '\'' || exit; [[ -z $REPLY || $REPLY = [Yy]* ]] && sudo poweroff || echo "Shutdown cancelled."'
alias ls='eza --icons --group-directories-first'
alias ll='eza -lh --icons --group-directories-first --time-style=long-iso'
alias la='eza -lha --icons --group-directories-first --time-style=long-iso'
alias tree='eza --tree --icons=auto'
alias grep='grep --color=auto'
alias pacclean='sudo pacman -Sc --noconfirm && sudo paccache -r'
alias fonts='fc-list : family | sort -u'
alias pacorphans='sudo pacman -Rns $(pacman -Qdtq) 2>/dev/null || echo "No orphans to remove."'
alias update='yay -Syu'
alias df='df -h'
alias n='nvim'
alias gs='git status -s'
alias ds='git diff --staged'
alias dsn='git diff --staged | diffnav'
alias ta='tmux attach'
alias tl='tmux list-sessions'
alias tkill='tmux kill-server'
alias tks='tmux kill-session -t'
alias ssh-on='_ssh_agent_lazy'
alias ruffle='env WGPU_PRESENT_MODE=Immediate ruffle --graphics vulkan'
alias stream='mpv "av://v4l2:/dev/video0" --fullscreen --demuxer-lavf-o=input_format=mjpeg,framerate=30 --profile=low-latency --untimed --vf=hflip'
